-- Band business / agency profile fields for Cat Bot
ALTER TABLE "Band" ADD COLUMN IF NOT EXISTS "addressLine1" TEXT;
ALTER TABLE "Band" ADD COLUMN IF NOT EXISTS "addressLine2" TEXT;
ALTER TABLE "Band" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "Band" ADD COLUMN IF NOT EXISTS "state" TEXT;
ALTER TABLE "Band" ADD COLUMN IF NOT EXISTS "country" TEXT DEFAULT 'US';
ALTER TABLE "Band" ADD COLUMN IF NOT EXISTS "businessType" TEXT;
ALTER TABLE "Band" ADD COLUMN IF NOT EXISTS "servicesOffered" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Band" ADD COLUMN IF NOT EXISTS "servicesOther" TEXT;
ALTER TABLE "Band" ADD COLUMN IF NOT EXISTS "productsOffered" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Band" ADD COLUMN IF NOT EXISTS "productsOther" TEXT;
ALTER TABLE "Band" ADD COLUMN IF NOT EXISTS "serviceAreaMiles" INTEGER;
ALTER TABLE "Band" ADD COLUMN IF NOT EXISTS "clientSearchRadiusMiles" INTEGER;
ALTER TABLE "Band" ADD COLUMN IF NOT EXISTS "websiteUrl" TEXT;
ALTER TABLE "Band" ADD COLUMN IF NOT EXISTS "facebookUrl" TEXT;
ALTER TABLE "Band" ADD COLUMN IF NOT EXISTS "instagramUrl" TEXT;
ALTER TABLE "Band" ADD COLUMN IF NOT EXISTS "xUrl" TEXT;
ALTER TABLE "Band" ADD COLUMN IF NOT EXISTS "tiktokUrl" TEXT;
ALTER TABLE "Band" ADD COLUMN IF NOT EXISTS "youtubeUrl" TEXT;

ALTER TABLE "Band" ALTER COLUMN "membershipRequirements" SET DEFAULT '';
ALTER TABLE "Band" ALTER COLUMN "skillsLookingFor" SET DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Band" ALTER COLUMN "whatMembersWillLearn" SET DEFAULT ARRAY[]::TEXT[];
